export type KanaSet = "basic" | "dakuten" | "combo";

export type KanaSourceCard = {
  romaji: string;
  hiragana: string;
  katakana: string;
  set: KanaSet;
};

export const KANA: KanaSourceCard[] = [
  { romaji: "a", hiragana: "あ", katakana: "ア", set: "basic" },
  { romaji: "i", hiragana: "い", katakana: "イ", set: "basic" },
  { romaji: "u", hiragana: "う", katakana: "ウ", set: "basic" },
  { romaji: "e", hiragana: "え", katakana: "エ", set: "basic" },
  { romaji: "o", hiragana: "お", katakana: "オ", set: "basic" },
  { romaji: "ka", hiragana: "か", katakana: "カ", set: "basic" },
  { romaji: "ki", hiragana: "き", katakana: "キ", set: "basic" },
  { romaji: "ku", hiragana: "く", katakana: "ク", set: "basic" },
  { romaji: "ke", hiragana: "け", katakana: "ケ", set: "basic" },
  { romaji: "ko", hiragana: "こ", katakana: "コ", set: "basic" },
  { romaji: "sa", hiragana: "さ", katakana: "サ", set: "basic" },
  { romaji: "shi", hiragana: "し", katakana: "シ", set: "basic" },
  { romaji: "su", hiragana: "す", katakana: "ス", set: "basic" },
  { romaji: "se", hiragana: "せ", katakana: "セ", set: "basic" },
  { romaji: "so", hiragana: "そ", katakana: "ソ", set: "basic" },
  { romaji: "ta", hiragana: "た", katakana: "タ", set: "basic" },
  { romaji: "chi", hiragana: "ち", katakana: "チ", set: "basic" },
  { romaji: "tsu", hiragana: "つ", katakana: "ツ", set: "basic" },
  { romaji: "te", hiragana: "て", katakana: "テ", set: "basic" },
  { romaji: "to", hiragana: "と", katakana: "ト", set: "basic" },
  { romaji: "na", hiragana: "な", katakana: "ナ", set: "basic" },
  { romaji: "ni", hiragana: "に", katakana: "ニ", set: "basic" },
  { romaji: "nu", hiragana: "ぬ", katakana: "ヌ", set: "basic" },
  { romaji: "ne", hiragana: "ね", katakana: "ネ", set: "basic" },
  { romaji: "no", hiragana: "の", katakana: "ノ", set: "basic" },
  { romaji: "ha", hiragana: "は", katakana: "ハ", set: "basic" },
  { romaji: "hi", hiragana: "ひ", katakana: "ヒ", set: "basic" },
  { romaji: "fu", hiragana: "ふ", katakana: "フ", set: "basic" },
  { romaji: "he", hiragana: "へ", katakana: "ヘ", set: "basic" },
  { romaji: "ho", hiragana: "ほ", katakana: "ホ", set: "basic" },
  { romaji: "ma", hiragana: "ま", katakana: "マ", set: "basic" },
  { romaji: "mi", hiragana: "み", katakana: "ミ", set: "basic" },
  { romaji: "mu", hiragana: "む", katakana: "ム", set: "basic" },
  { romaji: "me", hiragana: "め", katakana: "メ", set: "basic" },
  { romaji: "mo", hiragana: "も", katakana: "モ", set: "basic" },
  { romaji: "ya", hiragana: "や", katakana: "ヤ", set: "basic" },
  { romaji: "yu", hiragana: "ゆ", katakana: "ユ", set: "basic" },
  { romaji: "yo", hiragana: "よ", katakana: "ヨ", set: "basic" },
  { romaji: "ra", hiragana: "ら", katakana: "ラ", set: "basic" },
  { romaji: "ri", hiragana: "り", katakana: "リ", set: "basic" },
  { romaji: "ru", hiragana: "る", katakana: "ル", set: "basic" },
  { romaji: "re", hiragana: "れ", katakana: "レ", set: "basic" },
  { romaji: "ro", hiragana: "ろ", katakana: "ロ", set: "basic" },
  { romaji: "wa", hiragana: "わ", katakana: "ワ", set: "basic" },
  { romaji: "wo", hiragana: "を", katakana: "ヲ", set: "basic" },
  { romaji: "n", hiragana: "ん", katakana: "ン", set: "basic" },
  { romaji: "ga", hiragana: "が", katakana: "ガ", set: "dakuten" },
  { romaji: "gi", hiragana: "ぎ", katakana: "ギ", set: "dakuten" },
  { romaji: "gu", hiragana: "ぐ", katakana: "グ", set: "dakuten" },
  { romaji: "ge", hiragana: "げ", katakana: "ゲ", set: "dakuten" },
  { romaji: "go", hiragana: "ご", katakana: "ゴ", set: "dakuten" },
  { romaji: "za", hiragana: "ざ", katakana: "ザ", set: "dakuten" },
  { romaji: "ji", hiragana: "じ", katakana: "ジ", set: "dakuten" },
  { romaji: "zu", hiragana: "ず", katakana: "ズ", set: "dakuten" },
  { romaji: "ze", hiragana: "ぜ", katakana: "ゼ", set: "dakuten" },
  { romaji: "zo", hiragana: "ぞ", katakana: "ゾ", set: "dakuten" },
  { romaji: "da", hiragana: "だ", katakana: "ダ", set: "dakuten" },
  { romaji: "de", hiragana: "で", katakana: "デ", set: "dakuten" },
  { romaji: "do", hiragana: "ど", katakana: "ド", set: "dakuten" },
  { romaji: "ba", hiragana: "ば", katakana: "バ", set: "dakuten" },
  { romaji: "bi", hiragana: "び", katakana: "ビ", set: "dakuten" },
  { romaji: "bu", hiragana: "ぶ", katakana: "ブ", set: "dakuten" },
  { romaji: "be", hiragana: "べ", katakana: "ベ", set: "dakuten" },
  { romaji: "bo", hiragana: "ぼ", katakana: "ボ", set: "dakuten" },
  { romaji: "pa", hiragana: "ぱ", katakana: "パ", set: "dakuten" },
  { romaji: "pi", hiragana: "ぴ", katakana: "ピ", set: "dakuten" },
  { romaji: "pu", hiragana: "ぷ", katakana: "プ", set: "dakuten" },
  { romaji: "pe", hiragana: "ぺ", katakana: "ペ", set: "dakuten" },
  { romaji: "po", hiragana: "ぽ", katakana: "ポ", set: "dakuten" },
  { romaji: "kya", hiragana: "きゃ", katakana: "キャ", set: "combo" },
  { romaji: "kyu", hiragana: "きゅ", katakana: "キュ", set: "combo" },
  { romaji: "kyo", hiragana: "きょ", katakana: "キョ", set: "combo" },
  { romaji: "sha", hiragana: "しゃ", katakana: "シャ", set: "combo" },
  { romaji: "shu", hiragana: "しゅ", katakana: "シュ", set: "combo" },
  { romaji: "sho", hiragana: "しょ", katakana: "ショ", set: "combo" },
  { romaji: "cha", hiragana: "ちゃ", katakana: "チャ", set: "combo" },
  { romaji: "chu", hiragana: "ちゅ", katakana: "チュ", set: "combo" },
  { romaji: "cho", hiragana: "ちょ", katakana: "チョ", set: "combo" },
  { romaji: "nya", hiragana: "にゃ", katakana: "ニャ", set: "combo" },
  { romaji: "nyu", hiragana: "にゅ", katakana: "ニュ", set: "combo" },
  { romaji: "nyo", hiragana: "にょ", katakana: "ニョ", set: "combo" },
  { romaji: "hya", hiragana: "ひゃ", katakana: "ヒャ", set: "combo" },
  { romaji: "hyu", hiragana: "ひゅ", katakana: "ヒュ", set: "combo" },
  { romaji: "hyo", hiragana: "ひょ", katakana: "ヒョ", set: "combo" },
  { romaji: "mya", hiragana: "みゃ", katakana: "ミャ", set: "combo" },
  { romaji: "myu", hiragana: "みゅ", katakana: "ミュ", set: "combo" },
  { romaji: "myo", hiragana: "みょ", katakana: "ミョ", set: "combo" },
  { romaji: "rya", hiragana: "りゃ", katakana: "リャ", set: "combo" },
  { romaji: "ryu", hiragana: "りゅ", katakana: "リュ", set: "combo" },
  { romaji: "ryo", hiragana: "りょ", katakana: "リョ", set: "combo" },
  { romaji: "gya", hiragana: "ぎゃ", katakana: "ギャ", set: "combo" },
  { romaji: "gyu", hiragana: "ぎゅ", katakana: "ギュ", set: "combo" },
  { romaji: "gyo", hiragana: "ぎょ", katakana: "ギョ", set: "combo" },
  { romaji: "ja", hiragana: "じゃ", katakana: "ジャ", set: "combo" },
  { romaji: "ju", hiragana: "じゅ", katakana: "ジュ", set: "combo" },
  { romaji: "jo", hiragana: "じょ", katakana: "ジョ", set: "combo" },
  { romaji: "bya", hiragana: "びゃ", katakana: "ビャ", set: "combo" },
  { romaji: "byu", hiragana: "びゅ", katakana: "ビュ", set: "combo" },
  { romaji: "byo", hiragana: "びょ", katakana: "ビョ", set: "combo" },
  { romaji: "pya", hiragana: "ぴゃ", katakana: "ピャ", set: "combo" },
  { romaji: "pyu", hiragana: "ぴゅ", katakana: "ピュ", set: "combo" },
  { romaji: "pyo", hiragana: "ぴょ", katakana: "ピョ", set: "combo" },
];
